//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomicAssetsClient.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Samples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Samples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtomicAssetsClient.Data.Samples", typeof(Samples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;success&quot;: true,
        ///  &quot;data&quot;: {
        ///    &quot;contract&quot;: &quot;atomicassets&quot;,
        ///    &quot;asset_id&quot;: &quot;1099511627776&quot;,
        ///    &quot;owner&quot;: &quot;intqi.wam&quot;,
        ///    &quot;is_transferable&quot;: true,
        ///    &quot;is_burnable&quot;: true,
        ///    &quot;collection&quot;: {
        ///      &quot;collection_name&quot;: &quot;atomic&quot;,
        ///      &quot;name&quot;: &quot;Official AtomicAssets&quot;,
        ///      &quot;img&quot;: &quot;QmYeWdTRTEePZasagQaT4UkuRbfe1sPvyw47PZrroba9tH&quot;,
        ///      &quot;author&quot;: &quot;atomic&quot;,
        ///      &quot;allow_notify&quot;: true,
        ///      &quot;authorized_accounts&quot;: [
        ///        &quot;atomic&quot;
        ///      ],
        ///      &quot;notify_accounts&quot;: [],
        ///      &quot;market_fee&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAsset {
            get {
                return ResourceManager.GetString("GetAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;success&quot;: true,
        ///  &quot;data&quot;: {
        ///    &quot;contract&quot;: &quot;atomicassets&quot;,
        ///    &quot;collection_name&quot;: &quot;atomic&quot;,
        ///    &quot;name&quot;: &quot;Official AtomicAssets&quot;,
        ///    &quot;img&quot;: &quot;QmYeWdTRTEePZasagQaT4UkuRbfe1sPvyw47PZrroba9tH&quot;,
        ///    &quot;author&quot;: &quot;atomic&quot;,
        ///    &quot;allow_notify&quot;: true,
        ///    &quot;authorized_accounts&quot;: [
        ///      &quot;atomic&quot;
        ///    ],
        ///    &quot;notify_accounts&quot;: [ &quot;test1&quot;, &quot;test2&quot; ],
        ///    &quot;market_fee&quot;: 0.12,
        ///    &quot;data&quot;: {
        ///      &quot;img&quot;: &quot;QmYeWdTRTEePZasagQaT4UkuRbfe1sPvyw47PZrroba9tH&quot;,
        ///      &quot;url&quot;: &quot;https://atomicassets.io/&quot;,
        ///      &quot;name [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetCollection {
            get {
                return ResourceManager.GetString("GetCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;success&quot;: true,
        ///  &quot;data&quot;: {
        ///    &quot;contract&quot;: &quot;atomicassets&quot;,
        ///    &quot;schema_name&quot;: &quot;awards&quot;,
        ///    &quot;format&quot;: [
        ///      {        &quot;name&quot;: &quot;name&quot;,        &quot;type&quot;: &quot;string&quot;      },
        ///      {        &quot;name&quot;: &quot;img&quot;,        &quot;type&quot;: &quot;ipfs&quot;      },
        ///      {        &quot;name&quot;: &quot;mint&quot;,        &quot;type&quot;: &quot;uint64&quot;      },
        ///      {        &quot;name&quot;: &quot;description&quot;,        &quot;type&quot;: &quot;string&quot;      }
        ///    ],
        ///    &quot;collection&quot;: {
        ///      &quot;collection_name&quot;: &quot;atomic&quot;,
        ///      &quot;name&quot;: &quot;Official AtomicAssets&quot;,
        ///      &quot;img&quot;: &quot;QmYeWdTRTEePZasagQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetSchema {
            get {
                return ResourceManager.GetString("GetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;success&quot;: true,
        ///  &quot;data&quot;: {
        ///    &quot;contract&quot;: &quot;atomicassets&quot;,
        ///    &quot;template_id&quot;: &quot;1&quot;,
        ///    &quot;is_transferable&quot;: true,
        ///    &quot;is_burnable&quot;: true,
        ///    &quot;issued_supply&quot;: &quot;154&quot;,
        ///    &quot;max_supply&quot;: &quot;1540&quot;,
        ///    &quot;collection&quot;: {
        ///      &quot;collection_name&quot;: &quot;atomic&quot;,
        ///      &quot;name&quot;: &quot;Official AtomicAssets&quot;,
        ///      &quot;img&quot;: &quot;QmYeWdTRTEePZasagQaT4UkuRbfe1sPvyw47PZrroba9tH&quot;,
        ///      &quot;author&quot;: &quot;atomic&quot;,
        ///      &quot;allow_notify&quot;: true,
        ///      &quot;authorized_accounts&quot;: [
        ///        &quot;atomic&quot;
        ///      ],
        ///      &quot;notify_accounts&quot;: [],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetTemplate {
            get {
                return ResourceManager.GetString("GetTemplate", resourceCulture);
            }
        }
    }
}
